In [1]:
import numpy as np

In [2]:
input_feature = np.array([[0,0],[0,1],[1,0],[1,1]])
print(input_feature.shape)
input_feature

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
target_output = np.array([[0,1,1,1]])
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [4]:
weights = np.array([[0.1],[0.2]])
weights.shape

(2, 1)

In [5]:
bias = 0.3
lr = 0.05

In [6]:
def sigmoid(x):
    return 1/(1+np.exp(-x)) 

In [7]:
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [8]:
# main logic

for epoch in range(1000):
    inputs = input_feature
    
    #forward
    in_o = np.dot(inputs,weights) + bias
    
    out_o = sigmoid(in_o)
    
    #back
    error = out_o - target_output
    
    x = error.sum()
    #print(x)
    
    
    derror_douto = error
    
    douto_dino = sigmoid_der(out_o)
    
    deriv = derror_douto *  douto_dino
    
   
    
    inputs = input_feature.T
    deriv_final = np.dot(inputs,deriv)
    
    weights -= lr * deriv_final
    
    for i in deriv:
        bias -= lr * i 
    


In [9]:
print(weights)

[[2.64321662]
 [2.66226811]]


In [10]:
print(bias)

[-0.77937434]


In [13]:
#predict

single_point = np.array([1,0])
result1 = np.dot(single_point , weights) + bias
result2 = sigmoid(result1)
print(result2)

[0.86574417]


In [12]:
single_point = np.array([0,0]) #1st step:
result1 = np.dot(single_point, weights) + bias #2nd step:
result2 = sigmoid(result1) #Pri

In [13]:
result2

array([0.31445475])